language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    fast_finish: true
git:
    submodules: false
before_install:
    - apt-get install -y binaryen
    - docker pull sagansoftware/eos:latest
install:
    - rustup target add wasm32-unknown-unknown
    - rustup component add rustfmt
    - cargo install wasm-gc
services:
    - docker
script:
    - bash scripts/test.sh
