[profile.release]
opt-level = "s"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false

[workspace]
members = [
    "eosio",
    "eosio_abi",
    "eosio_bytes",
    "eosio_bytes_derive",
    "eosio_cdt_sys",
    # "eosio_cli", TODO re-enable
    "eosio_contracts/eosio_system",
    "eosio_contracts/eosio_token",
    "eosio_macros_impl",
    "eosio_macros",
    "eosio_rpc",
    "examples/addressbook",
    "examples/hello_bare",
    "examples/hello",
    "examples/tictactoe",
]
