[profile.release]
opt-level = "s"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false

[workspace]
members = [
    "crates/eosio_abi",
    "crates/eosio_cli",
    "crates/eosio_macros_impl",
    "crates/eosio_macros",
    "crates/eosio_rpc",
    "crates/eosio_sys",
    "crates/eosio_system",
    "crates/eosio_token",
    "crates/eosio",
    "examples/addressbook",
    "examples/hello_bare",
    "examples/hello",
    "examples/tictactoe",
]
