[profile.release]
lto = true
opt-level = "s"
debug = false
panic = "abort"

[workspace]
members = [
    "contracts/eosio_system",
    "contracts/eosio_token",
    "crates/eosio_abi",
    "crates/eosio_cli",
    "crates/eosio_macros_impl",
    "crates/eosio_macros",
    "crates/eosio_rpc",
    "crates/eosio_sys",
    "crates/eosio",
    "examples/addressbook",
    "examples/hello_bare",
    "examples/hello",
    "examples/tictactoe"
]
