[profile.release]
opt-level = "s"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false

[workspace]
members = [
    "eosio",
    # "eosio_abi",
    "eosio_bytes",
    "eosio_bytes_derive",
    "eosio_cdt",
    "eosio_cdt_macros",
    "eosio_cdt_macros/impl",
    "eosio_cdt_sys",
    # "eosio_cli", TODO re-enable
    # "eosio_contracts/eosio_system",
    "eosio_contracts/eosio_token",
    "eosio_core",
    "eosio_numstr",
    "eosio_numstr_macros",
    "eosio_numstr_macros/impl",
    # "eosio_rpc",
    "examples/addressbook",
    "examples/hello_bare",
    "examples/hello",
    "examples/tictactoe",
]

[package]
name = "eosio-rust"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[dev-dependencies]
criterion = "0.2"
eosio_numstr = { path = "./eosio_numstr" }

[[bench]]
name = "bench_main"
harness = false

[features]
contract = []