[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[workspace]
members = [
    "benchmarks",
    "eosio",
    # "eosio_abi",
    "eosio_bytes",
    "eosio_bytes_derive",
    "eosio_cdt",
    "eosio_cdt_macros",
    "eosio_cdt_macros_impl",
    "eosio_cdt_sys",
    # "eosio_cli", TODO re-enable
    "eosio_contracts/eosio_assert",
    "eosio_contracts/eosio_bios",
    "eosio_contracts/eosio_forum",
    "eosio_contracts/eosio_msig",
    "eosio_contracts/eosio_system",
    "eosio_contracts/eosio_token",
    "eosio_contracts/eosio_wrap",
    "eosio_core",
    "eosio_numstr",
    "eosio_numstr_macros",
    "eosio_numstr_macros_impl",
    # "eosio_rpc",
    "examples/addressbook",
    "examples/hello_bare",
    "examples/hello",
    "examples/tictactoe",
]
