[profile.release]
lto = true
opt-level = "s"
debug = false
panic = "abort"

[workspace]
members = [
    "crates/eosio",
    "crates/eosio_macros",
    "crates/eosio_macros_impl",
    "crates/eosio_rpc",
    "crates/eosio_sys",
    "crates/eosio_token",
    "examples/addressbook",
    "examples/hello",
    "examples/hello_bare",
    "examples/tictactoe",
    "examples/tictactoe_ui"
]
