[package]
name = "hello"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
test = false

[dependencies]
eosio = { path = "../../eosio" }
