version: "3"

services:
  nodeosd:
    build:
      dockerfile: ./eos.dockerfile
      context: .
    image: sagansoftware/eos:2.0.0
    hostname: nodeosd
    entrypoint: nodeos
    command: >
      --contracts-console
      --data-dir /eos/build/data-dir
      --plugin eosio::http_plugin
      --http-server-address=0.0.0.0:8888
      --https-server-address=0.0.0.0:8889
      --access-control-allow-origin=*
      --access-control-allow-credentials
      --verbose-http-errors
      --http-alias=nodeosd:8888
      --http-alias=127.0.0.1:8888
      --http-alias=localhost:8888
      --http-alias=nodeosd:8889
      --http-alias=127.0.0.1:8889
      --http-alias=localhost:8889
      --plugin eosio::producer_plugin
      --enable-stale-production
      --producer-name=eosio
      --plugin eosio::chain_api_plugin
      --plugin eosio::history_api_plugin
    ports:
      - 8888:8888
      - 8889:8889
      - 9876:9876
    expose:
      - "8888"
      - "8889"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    build:
      dockerfile: ./eos.dockerfile
      context: .
    image: sagansoftware/eos:2.0.0
    hostname: keosd
    entrypoint: keosd
    command: >
      --wallet-dir /opt/eosio/bin/data-dir
      --unlock-timeout 9999999
      --http-server-address=127.0.0.1:8900
      --http-alias=keosd:8900
      --http-alias=localhost:8900
    ports:
      - 8900:8900
    expose:
      - "8900"
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ../target/wasm32-unknown-unknown/release:/mnt/dev/release:ro
      - ../examples:/mnt/dev/examples:ro
      - ../:/mnt/dev/project:ro
    links:
      - nodeosd
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
