[package]
name = "eosio"
version = "0.2.0"
authors = ["Liam Curry <liam@sagan.software>"]
license = "MIT/Apache-2.0"
description = "Library for building EOSIO smart contracts"
edition = "2018"

[features]
default = ["std"]
std = []
alloc = []
contract = []

[dependencies]
eosio_bytes = { path = "../eosio_bytes", features = ["derive", "internal-use-only-root-path-is-eosio"] }
eosio_core = { path = "../eosio_core" }
eosio_cdt = { path = "../eosio_cdt" }
eosio_cdt_macros = { path = "../eosio_cdt_macros", features = ["internal"] }
eosio_cdt_sys = { path = "../eosio_cdt_sys" }
eosio_numstr_macros = { path = "../eosio_numstr_macros" }
