[package]
name = "eosio"
version = "0.2.0"
authors = ["Liam Curry <liam@sagan.software>"]
license = "MIT/Apache-2.0"
description = "Library for building EOSIO smart contracts"
edition = "2018"

[features]
default = ["std"]
std = []
alloc = []
contract = ["eosio_macros/contract"]

[dependencies]
eosio_bytes = { path = "../eosio_bytes" }
eosio_macros = { path = "../eosio_macros", features = ["internal"] }
eosio_cdt_sys = { path = "../eosio_cdt_sys" }
serde = { version = "1.0", optional = true, features = ["derive"] }
wasm-bindgen = { version = "0.2", optional = true }
stdweb = { version = "0.4.14", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", optional = true }
static_assertions = "0.3.1"
mashup = "0.1"
