[package]
name = "eosio_system"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
eosio = { path = "../../crates/eosio", features = ["serde"] }
