[package]
name = "benchmarks"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[dependencies]
plotters = "0.2.1"
regex = "1"
lazy_static = "1.3"
rand = "0.6"
eosio-core = { version = "0.2", path = "../eosio-core" }