[package]
name = "eosio_rpc"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
eosio = { path = "../eosio", features = ["serde"] }
futures = "0.1.20"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]  }
js-sys = "0.3.5"
wasm-bindgen-futures = "0.3.5"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]
