[package]
name = "eosio_rpc"
version = "0.1.0"
authors = ["Liam Curry <liam@sagan.software>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
eosio = { path = "../eosio", features = ["serde"] }
